In [ ]:
['x','b','r','q'] -> ['b','q','r','x']

[7,2,4,8] -> [2,4,7,8]

In [1]:
sorted([7,2,4,8])

[2, 4, 7, 8]

In [3]:
def print_pass(data,pass_number,index):
    label = f'after pass {pass_number}: '
    print(label,end='')
    #output elements
    print('  '.join(str(d) for d in data[:index]), end='  ' if index!=0 else '')
    print(f'{data[index]}* ',end='')
    print('  '.join(str(d) for d in data[index+1:len(data)]))
    print(f'{" "*len(label)}{"--  "*pass_number}')

In [17]:
def selection_sort(data):
    for index1 in range(len(data)-1):
        smallest = index1
        for index2 in range(index1+1,len(data)):
            if data[index2]<data[smallest]:
                smallest = index2
                #print('index1: ',index1,'index2: ',index2)
                
        #swap smallest element into position
        data[smallest],data[index1] = data[index1],data[smallest]
        print_pass(data,index1+1,smallest)
    return data

In [18]:
import numpy as np
data = np.array([35,73,90,65,23,86,43,81,34,58])

selection_sort(data)

after pass 1: 23  73  90  65  35* 86  43  81  34  58
              --  
after pass 2: 23  34  90  65  35  86  43  81  73* 58
              --  --  
after pass 3: 23  34  35  65  90* 86  43  81  73  58
              --  --  --  
after pass 4: 23  34  35  43  90  86  65* 81  73  58
              --  --  --  --  
after pass 5: 23  34  35  43  58  86  65  81  73  90* 
              --  --  --  --  --  
after pass 6: 23  34  35  43  58  65  86* 81  73  90
              --  --  --  --  --  --  
after pass 7: 23  34  35  43  58  65  73  81  86* 90
              --  --  --  --  --  --  --  
after pass 8: 23  34  35  43  58  65  73  81* 86  90
              --  --  --  --  --  --  --  --  
after pass 9: 23  34  35  43  58  65  73  81  86* 90
              --  --  --  --  --  --  --  --  --  


array([23, 34, 35, 43, 58, 65, 73, 81, 86, 90])

In [ ]:
def selection_sort(data):
    for index1 in range(len(data)-1):
        smallest = index1
        for index2 in range(index1+1,len(data)):
            if data[index2]<data[smallest]:
                smallest = index2
        data[smallest],data[index1] = data[index1],data[smallest]
    return data

In [9]:
def insertion_sort(data):
    for Next in range(1,len(data)):
        insert = data[Next]
        move_item = Next
        
        while move_item>0 and data[move_item-1]>insert:
            data[move_item] = data[move_item - 1]
            move_item -=1
            #print('index1: ',Next,' index2: ',move_item)
        data[move_item] = insert
        print_pass(data,Next,move_item)
    return data

In [10]:
data = np.array([35,73,90,65,23,86,43,81,34,58])
print(data)
insertion_sort(data)

[35 73 90 65 23 86 43 81 34 58]
after pass 1: 35  73* 90  65  23  86  43  81  34  58
              --  
after pass 2: 35  73  90* 65  23  86  43  81  34  58
              --  --  
after pass 3: 35  65* 73  90  23  86  43  81  34  58
              --  --  --  
after pass 4: 23* 35  65  73  90  86  43  81  34  58
              --  --  --  --  
after pass 5: 23  35  65  73  86* 90  43  81  34  58
              --  --  --  --  --  
after pass 6: 23  35  43* 65  73  86  90  81  34  58
              --  --  --  --  --  --  
after pass 7: 23  35  43  65  73  81* 86  90  34  58
              --  --  --  --  --  --  --  
after pass 8: 23  34* 35  43  65  73  81  86  90  58
              --  --  --  --  --  --  --  --  
after pass 9: 23  34  35  43  58* 65  73  81  86  90
              --  --  --  --  --  --  --  --  --  


array([23, 34, 35, 43, 58, 65, 73, 81, 86, 90])

In [19]:
L = [4,5,2,1]
insertion_sort(L)

TypeError: 'tuple' object does not support item assignment

In [13]:
def insertion_sort(data):
    for Next in range(1,len(data)):
        insert = data[Next]
        move_item = Next
        
        while move_item>0 and data[move_item-1]>insert:
            data[move_item] = data[move_item - 1]
            move_item -=1
            
        data[move_item] = insert
    return data

In [24]:
import numpy as np


def subarray_string(data,low,high):
    temp = '  '*low
    temp += ' '.join(str(item) for item in data[low:high+1])
    return temp

def sort_array_p(data,low,high):
    """Split data, sort subarrays and merge them into a sorted array."""
    #test base case size of array equals 1
    if (high-low)>=1: #if not base case
        middle1 = (low+high)//2 #calculate the middle of array
        middle2 = middle1 + 1
        
        #output split step
        print(f'split: {subarray_string(data,low,high)}')
        print(f'       {subarray_string(data,low,middle1)}')
        print(f'       {subarray_string(data,middle2,high)}\n')
        
        #split array in half then sort each half (recursive calls)
        sort_array_p(data,low,middle1)
        sort_array_p(data,middle2,high)
        return merge_p(data,low,middle1,middle2,high)
        
def merge_p(data,left,middle1,middle2,right):
    left_index = left #index into left subarray
    right_index = middle2 #index into right subarray
    combined_index = left #index into temporary working array
    merged = [0]*len(data) #working array
    
    #output two subarrays before merging
    print(f'merge: {subarray_string(data,left,middle1)}')
    print(f'       {subarray_string(data,middle2,right)}')
    
    #merge arrays until reaching end of either
    while left_index <= middle1 and right_index <= right:#place smaller of two current elements into result and move to next space in arrays
        if data[left_index]<=data[right_index]:
            merged[combined_index] = data[left_index]
            combined_index+=1
            left_index+=1
        else:
            merged[combined_index]=data[right_index]
            combined_index+=1
            right_index+=1
            
    #if left array is empty
    if left_index == middle2: #if true, copy in rest of right array
        merged[combined_index:right+1] = data[right_index:right+1]
    else: #right array is empty, copy in rest of left array
        merged[combined_index:right+1] = data[left_index:middle1+1]
        
    data[left:right+1] = merged[left:right+1]
    print(f'         {subarray_string(data,left,right)}\n')
    return data
    
def merge_sort_p(data):
    return sort_array_p(data,0,len(data)-1)

In [26]:
data = np.array( )
data1 = data.copy()
print(data)
data2 = merge_sort_p(data)
print(data1)
print(data2)

[35 73 90 65 23 86 43 81 34 58]
split: 35 73 90 65 23 86 43 81 34 58
       35 73 90 65 23
                 86 43 81 34 58

split: 35 73 90 65 23
       35 73 90
             65 23

split: 35 73 90
       35 73
           90

split: 35 73
       35
         73

merge: 35
         73
         35 73

merge: 35 73
           90
         35 73 90

split:       65 23
             65
               23

merge:       65
               23
               23 65

merge: 35 73 90
             23 65
         23 35 65 73 90

split:           86 43 81 34 58
                 86 43 81
                       34 58

split:           86 43 81
                 86 43
                     81

split:           86 43
                 86
                   43

merge:           86
                   43
                   43 86

merge:           43 86
                     81
                   43 81 86

split:                 34 58
                       34
                         58

merge:                 34
  

In [ ]:
import numpy as np


def sort_array(data,low,high):
    #test base case size of array equals 1
    if (high-low)>=1: #if not base case
        middle1 = (low+high)//2 #calculate the middle of array
        middle2 = middle1 + 1  
        #split array in half then sort each half (recursive calls)
        sort_array(data,low,middle1)
        sort_array(data,middle2,high)
        return merge(data,low,middle1,middle2,high)
        
def merge(data,left,middle1,middle2,right):
    left_index = left #index into left subarray
    right_index = middle2 #index into right subarray
    combined_index = left #index into temporary working array
    merged = [0]*len(data) #working array
    #merge arrays until reaching end of either
    while left_index <= middle1 and right_index <= right:#place smaller of two current elements into result and move to next space in arrays
        if data[left_index]<=data[right_index]:
            merged[combined_index] = data[left_index]
            combined_index+=1
            left_index+=1
        else:
            merged[combined_index]=data[right_index]
            combined_index+=1
            right_index+=1
    #if left array is empty
    if left_index == middle2: #if true, copy in rest of right array
        merged[combined_index:right+1] = data[right_index:right+1]
    else: #right array is empty, copy in rest of left array
        merged[combined_index:right+1] = data[left_index:middle1+1]
        
    data[left:right+1] = merged[left:right+1]
    return data
    
def merge_sort(data):
    return sort_array(data,0,len(data)-1)

In [27]:
def print_statement(statement): 
    print('0')

In [ ]:
def print_list_elements(L):
    for j in L:
        print(j)

In [28]:
def print_list_twice(L1):
    for i in L1:
        for j in L1:
            print(i,j)

In [ ]:
def function1():
    #step 1 - > O(a)
    #step 2 - > O(b)

In [ ]:
def two_list_prin(A,B):
    for i in A:
        for j in B:
            print(i,j)