In [1]:
from sklearn.datasets import make_regression

X,y = make_regression(n_samples=1000, n_features=2, n_targets=1)
X,y

(array([[-0.34816894,  0.08944952],
        [ 0.88849248, -0.46038791],
        [ 2.11091242,  0.54249007],
        ...,
        [ 0.88839314,  0.2664686 ],
        [-0.71739498,  1.94350877],
        [ 0.3448485 , -1.95095773]]),
 array([ 5.60642248e+00, -3.70481295e+01,  7.22886476e+01,  3.48983676e+01,
         5.90241469e+01, -2.68971093e+01, -1.09503718e+02, -1.24782154e+02,
         3.74963154e+01,  5.70775631e+01, -1.25423134e+02,  1.17529802e+01,
         8.86333307e+01, -9.18469689e+01, -2.19190360e+02,  1.06479546e+02,
         3.72351889e+01, -1.08115549e+02, -6.01868587e+01, -9.77857671e+01,
        -1.72568378e+02, -2.22538473e+01,  3.31185264e+01,  7.27649690e+01,
        -5.82827402e+01, -1.70271772e+02, -1.76509215e+02, -1.08215185e+02,
         6.44535740e+01,  5.44964261e+01, -1.28442731e+01,  9.24219343e+01,
         5.75025563e+01,  1.33058892e+02, -1.46830580e+02,  9.33582180e+00,
        -5.83777677e+01,  1.23414786e+02, -4.42030726e+01,  5.00833927e+01,
        -

In [5]:
import numpy as np

corr = np.corrcoef(X,X)
corr

array([[ 1., -1., -1., ..., -1.,  1., -1.],
       [-1.,  1.,  1., ...,  1., -1.,  1.],
       [-1.,  1.,  1., ...,  1., -1.,  1.],
       ...,
       [-1.,  1.,  1., ...,  1., -1.,  1.],
       [ 1., -1., -1., ..., -1.,  1., -1.],
       [-1.,  1.,  1., ...,  1., -1.,  1.]])

In [6]:
X

array([[-0.34816894,  0.08944952],
       [ 0.88849248, -0.46038791],
       [ 2.11091242,  0.54249007],
       ...,
       [ 0.88839314,  0.2664686 ],
       [-0.71739498,  1.94350877],
       [ 0.3448485 , -1.95095773]])