# User Defined Function (example from last week)
---

In [ ]:
# Does a string contain any substrings that are palindromes?
## Palindrome: a string that reads the same forwards and backwards

# first, create a function that checks if a string is a palindrome
# second, create a function that gets all the substrings of a given string
# third, prints all substrings of a string that are palindromes

In [5]:
# checks if a string is a palindrome
def testing_palindrome(word:str):
    # reverse the word
    reverse_word = word[::-1]
    # compare reverse and word
    if reverse_word.lower() == word.lower():
        return True
    else:
        return False

In [14]:
testing_palindrome("t")

True

In [7]:
testing_palindrome("Racecar")

True

In [19]:
# function that gets all the substrings of a given string
def get_substrings(full_string:str):
    
    # create a list to put substrings in
    substrings = []
    
    for i in range(len(full_string)):
        for j in range(i, len(full_string)):
            #print('{}:{}'.format(i,j+1))
            #print(full_string[i:j+1])
            #print('\n')
            substrings.append(full_string[i:j+1])
            
    substrings = set(substrings)
    return substrings
test_substrings = get_substrings("testing")
#print(test_substrings)

In [15]:
# prints all substrings of a string that are palindromes
def print_substring_palindromes(a_string:str):
    
    substrings = get_substrings(a_string)
    
    for s in substrings:
        
        if len(s) > 1 and testing_palindrome(s) == True:
            
            print(s)

In [16]:
print_substring_palindromes("google")

goog
oo


In [20]:
print_substring_palindromes("DataScience542")

ata


# NumPy examples
---

In [21]:
import numpy as np

In [22]:
# make a list of 10,000,000 integers as a ndarray and python list

my_list = list(range(0,10000000))

np_arr = np.arange(10000000)

In [23]:
# how long will it take to multiply that list by 2, ten differnt times

%time for i in range(10): np_arr = np_arr * 2

CPU times: user 60.4 ms, sys: 31.7 ms, total: 92.1 ms
Wall time: 101 ms


In [24]:
%time for i in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 4.19 s, sys: 575 ms, total: 4.76 s
Wall time: 4.8 s


In [ ]:
# numpy is usually between 10 and 100 times faster than a python list

In [25]:
test_list = [1,2,3,4]
test_list * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [26]:
arr = np.array([[1,2,3], [4,5,6]])

In [27]:
type(arr)

numpy.ndarray

In [28]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
arr[0]

array([1, 2, 3])

In [36]:
arr[1]#[1]

5

In [31]:
arr[1][1]

5

In [37]:
arr_3d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

In [38]:
arr_3d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
arr_3d.shape

(3, 3)

In [40]:
arr_3d.size

9

In [41]:
print(arr_3d.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


# Intro to Pandas
---

In [42]:
import pandas as pd

data = {"Ohio" : 35000,
       "Texas" : 71000,
       "Orgeon" : 16000,
       "Utah" : 5000}

series_example = pd.Series(data)

2023-06-27 20:54:28,644 [9858] INFO     numexpr.utils: Note: NumExpr detected 10 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2023-06-27 20:54:28,644 [9858] INFO     numexpr.utils: NumExpr defaulting to 8 threads.


In [45]:
series_example#.index

Ohio      35000
Texas     71000
Orgeon    16000
Utah       5000
dtype: int64

In [6]:
series_example.index

Index(['Ohio', 'Texas', 'Orgeon', 'Utah'], dtype='object')

In [7]:
series_example.shape

(4,)

In [46]:
# create Series from a list

series_example_2 = pd.Series([4, 7, -5, 3])

In [47]:
series_example_2

0    4
1    7
2   -5
3    3
dtype: int64

In [48]:
series_example_2.index = ["Bob", "Tracy", "Lauren", "Lisa"]

In [50]:
series_example_2

Bob       4
Tracy     7
Lauren   -5
Lisa      3
dtype: int64

In [51]:
series_example_2.index.name = "Salespeople"

In [52]:
series_example_2

Salespeople
Bob       4
Tracy     7
Lauren   -5
Lisa      3
dtype: int64

In [53]:
# create a dataframe from a dictionary

data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
       "year" : [2000, 2001, 2002, 2000, 2001, 2002],
       "population" : [1.5, 1.7, 1.8, 2.4, 2.9, 3.2]}

df = pd.DataFrame(data)

In [54]:
df

state  year  population
0    Ohio  2000         1.5
1    Ohio  2001         1.7
2    Ohio  2002         1.8
3  Nevada  2000         2.4
4  Nevada  2001         2.9
5  Nevada  2002         3.2

In [57]:
df.head()

state  year  population
0    Ohio  2000         1.5
1    Ohio  2001         1.7
2    Ohio  2002         1.8
3  Nevada  2000         2.4
4  Nevada  2001         2.9

In [58]:
df.tail()

state  year  population
1    Ohio  2001         1.7
2    Ohio  2002         1.8
3  Nevada  2000         2.4
4  Nevada  2001         2.9
5  Nevada  2002         3.2

In [59]:
df.columns

Index(['state', 'year', 'population'], dtype='object')

In [60]:
for c in df.columns:
    print(f"doing something with column {c}")

doing something with column state
doing something with column year
doing something with column population


In [61]:
for c in df.columns:
    print("doing something with column {}".format(c))

doing something with column state
doing something with column year
doing something with column population


In [62]:
df["growth"] = df['population'].apply(lambda x: 10*x/2)

In [63]:
df

state  year  population  growth
0    Ohio  2000         1.5     7.5
1    Ohio  2001         1.7     8.5
2    Ohio  2002         1.8     9.0
3  Nevada  2000         2.4    12.0
4  Nevada  2001         2.9    14.5
5  Nevada  2002         3.2    16.0

In [28]:
# create a dataframe from a list

# initialize list of lists
data = [["tom", 10], ["nick", 15], ["julie", 14]]

df2 = pd.DataFrame(data, columns = ["Name", "Age"])

In [29]:
df2

Name  Age
0    tom   10
1   nick   15
2  julie   14