# DS 542 Week 6
---

### Review of Functions from Week 5

In [1]:
# function example #1

# function to test if a word is a palindrome
# a palindrome is a word that reads the same forwards and backwards

def testing_palindrome(word: str):
    
    # variable of word reversed
    reversed_word = word[::-1]
    
    if word.lower() == reversed_word.lower():
        return True
    
    else:
        return False

In [2]:
testing_palindrome(word = "Michael")

False

In [3]:
testing_palindrome(word = "Racecar")

True

In [5]:
# funtion example #2

"Bookcase"

# function to get all substrings of a string
def getting_substrings(full_string: str):
    
    # create an empty list to hold all the substrings
    substrings = []
    
    # loop through the full_string one letter at a time
    for i in range(0, len(full_string)):
        
        for j in range(i, len(full_string)):
            
            # append the substring to our empty list
            substrings.append(full_string[i:j+1])
            
    # convert the list to a set, it will remove duplicates
    substrings = set(substrings)
    
    return substrings

In [6]:
getting_substrings(full_string = "test")

{'e', 'es', 'est', 's', 'st', 't', 'te', 'tes', 'test'}

In [7]:
# function example 3

# function to test if any substring of a string is a palindrome

def testing_substring_palindromes(text: str):
    
    # first, create all substrings of text
    substrings = getting_substrings(full_string = text)
    
    for s in substrings:
        
        if testing_palindrome(s) == True and len(s) > 1:
            print(s)

In [8]:
testing_substring_palindromes(text = "google")

oo
goog


In [9]:
testing_substring_palindromes(text = "This is week 6 of DS 542. We will review the Midterm content.")

ll
 6 
ee


## Midterm Exam Review

Re-reading the slides from Week 1, what are the guiding principles of python?
- is python open-source?
- is python meant to be intuitive/easily readible?
- is python a compiled language, or a interpreted langauage?
- is python made only for data science?

In [10]:
# order of operations for integers and floats

5 // 2 + (3 ** 2)

11

In [11]:
# string slicing

name = "Alexander"

name[2:6]

'exan'

In [12]:
# string methods

# uppercase a string
name.upper()

'ALEXANDER'

In [13]:
name.lower()

'alexander'

In [14]:
name.isalpha()

True

In [15]:
# How to check data types?

type(name)

str

In [16]:
data = 9 ** 3 + 7 - 100 / 3.14

In [17]:
type(data)

float

In [18]:
# How can you add elements to a list?

prime_numbers = [2, 3, 5, 7]

In [19]:
# If you want to add only 1 element to a list, use .append()

prime_numbers.append(11)

In [20]:
prime_numbers

[2, 3, 5, 7, 11]

In [21]:
# If you want to add multiple elements to a list at once, use .extend()
prime_numbers.extend([13, 17])

In [22]:
prime_numbers

[2, 3, 5, 7, 11, 13, 17]

In [23]:
# What is the difference between mutable and immutable?

# If a data type is mutable, it allows 3 things:
## you can add to that data type
## you can remove from that data type
## you can rearrage the order of elements in the data type (only if the data type is ordered)

# examples of mutable data types
a_list = [1, 3, 6, 8, 90]
a_list.append(100)
# dictionaries, set

In [24]:
# examples of immutable data types?
## tuples
## strings

In [25]:
# what is ordered in python?
## an ordered data structure has index positions for each of the elements

type(name)

str

In [26]:
name[3]

'x'

In [31]:
# How would you print only the keys, or only the values from a dictionary?

coffee_menu = {"hot coffee" : "$2.75",
              "iced coffee" : "$3.50",
              "cold brew" : "$4.50"}

for i in coffee_menu.keys():
    print(i)

hot coffee
iced coffee
cold brew


In [30]:
coffee_menu.keys()

dict_keys(['hot coffee', 'iced coffee', 'cold brew'])

In [28]:
for v in coffee_menu.values():
    print(v)

$2.75
$3.50
$4.50


In [32]:
for item in coffee_menu.items():
    print(item)

('hot coffee', '$2.75')
('iced coffee', '$3.50')
('cold brew', '$4.50')


In [33]:
# What is a set in python?

# A set is a list without duplicates
# sets use {}

names = {"George", "Emilia", "Dileep", "George"}

In [34]:
names

{'Dileep', 'Emilia', 'George'}

In [35]:
shoe_sizes = [10, 7, 8.5, 7]

In [36]:
shoe_sizes = set(shoe_sizes)

In [37]:
shoe_sizes

{7, 8.5, 10}

In [38]:
# If Statement

# if, elif, elif, elif, else

favorite_integer = int(input("What is your favorite integer?"))

if favorite_integer > 99 or favorite_integer < -99:
    print("Your favorite integer is at least 3 digits long")
    
elif favorite_integer > 9 or favorite_integer < -9:
    print("Your favorite integer is 2 digits long")
    
else:
    print("Your favorite integer is 1 digit long")

What is your favorite integer?75
Your favorite integer is 2 digits long


In [39]:
# While Loop

# example to verify how many times a while loop is executed

counter = 0

i = 10
j = 2

while i > j:
    
    counter += 1
    i -= 3
    
print(f"value of the counter: {counter}")

value of the counter: 3


In [40]:
# function with a string method

# function to return the lowercase of any string entered as the arguement

def lowercase_string(x: str):
    
    return x.lower()

In [41]:
lowercase_string(x = "HELLO")

'hello'

In [42]:
# how to create a random integer

import random

# to create a random integer
random.randint(500, 1000)

678

In [43]:
# How could we create a function that returns triple the value of any number

def triple_number(x):
    
    return x * 3

In [44]:
triple_number(x = 9)

27

# NumPy Examples
---

In [3]:
import numpy as np

In [5]:
# make a list of 10 Million integers

# using python list
python_list = list(range(10000000))

# using an ndarray
numpy_array = np.arange(10000000)

In [13]:
# how long will it take to multiply every list element by 2, 10 times

# first, test the python list
%time 
for i in range(10): 
    python_list_2 = [x * 2 for x in python_list]

CPU times: user 2 µs, sys: 1 µs, total: 3 µs
Wall time: 5.96 µs


In [14]:
# now, test the same operation on the numpy list

%time 
for i in range(10): 
    numpy_array_2 = numpy_array * 2

CPU times: user 2 µs, sys: 1 µs, total: 3 µs
Wall time: 6.2 µs


In [49]:
# numpy is typically 10 to 100 times faster than built-in python operations on arrays

In [15]:
array = np.array([[1, 2, 3], 
                  [4, 5, 6]])

In [16]:
array

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
array.shape

(2, 3)

In [18]:
array_2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

In [19]:
array_2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [20]:
array_2 * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [21]:
array_2.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [1]:
def func1():
    print("I am learning python")

In [2]:
func1()

I am learning python
