# Exercise 7.14

In [1]:
import numpy as np

In [2]:
array1 = np.array([[0, 1], [2, 3]])

In [3]:
array1

array([[0, 1],
       [2, 3]])

In [4]:
array2 = np.array([[4, 5], [6, 7]])

In [5]:
array2

array([[4, 5],
       [6, 7]])

In [6]:
array3 = np.vstack((array1, array2))

In [7]:
array3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [8]:
array4 = np.hstack((array1, array2))

In [9]:
array4

array([[0, 1, 4, 5],
       [2, 3, 6, 7]])

In [10]:
array5 = np.vstack((array4, array4))

In [11]:
array5

array([[0, 1, 4, 5],
       [2, 3, 6, 7],
       [0, 1, 4, 5],
       [2, 3, 6, 7]])

In [12]:
array6 = np.hstack((array3, array3))

In [13]:
array6

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5],
       [6, 7, 6, 7]])

In [14]:
##########################################################################
# (C) Copyright 2019 by Deitel & Associates, Inc. and                    #
# Pearson Education, Inc. All Rights Reserved.                           #
#                                                                        #
# DISCLAIMER: The authors and publisher of this book have used their     #
# best efforts in preparing the book. These efforts include the          #
# development, research, and testing of the theories and programs        #
# to determine their effectiveness. The authors and publisher make       #
# no warranty of any kind, expressed or implied, with regard to these    #
# programs or to the documentation contained in these books. The authors #
# and publisher shall not be liable in any event for incidental or       #
# consequential damages in connection with, or arising out of, the       #
# furnishing, performance, or use of these programs.                     #
##########################################################################