# Exercise 7.3

In [1]:
import numpy as np

In [2]:
numbers1 = np.arange(2, 19, 2).reshape(3, 3)

In [3]:
numbers1

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [4]:
numbers2 = np.arange(9, 0, -1).reshape(3, 3)

In [5]:
numbers2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [6]:
numbers1 * numbers2

array([[18, 32, 42],
       [48, 50, 48],
       [42, 32, 18]])

In [7]:
##########################################################################
# (C) Copyright 2019 by Deitel & Associates, Inc. and                    #
# Pearson Education, Inc. All Rights Reserved.                           #
#                                                                        #
# DISCLAIMER: The authors and publisher of this book have used their     #
# best efforts in preparing the book. These efforts include the          #
# development, research, and testing of the theories and programs        #
# to determine their effectiveness. The authors and publisher make       #
# no warranty of any kind, expressed or implied, with regard to these    #
# programs or to the documentation contained in these books. The authors #
# and publisher shall not be liable in any event for incidental or       #
# consequential damages in connection with, or arising out of, the       #
# furnishing, performance, or use of these programs.                     #
##########################################################################