# Exercise 7.9

In [1]:
import numpy as np

In [2]:
numbers = np.arange(1, 16).reshape(3, 5)

In [3]:
numbers

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [4]:
# Part a
numbers[2]

array([11, 12, 13, 14, 15])

**INSTRUCTOR NOTE: Part b should say "Select column 4"

In [5]:
# Part b
numbers[:, 4]

array([ 5, 10, 15])

In [6]:
# Part c
numbers[:, 0:2]

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

In [7]:
# Part d
numbers[:, 2:5]

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15]])

In [8]:
# Part e
numbers[1, 4]

10

In [9]:
# Part f
numbers[1:3, [0, 2, 4]]

array([[ 6,  8, 10],
       [11, 13, 15]])

In [10]:
##########################################################################
# (C) Copyright 2019 by Deitel & Associates, Inc. and                    #
# Pearson Education, Inc. All Rights Reserved.                           #
#                                                                        #
# DISCLAIMER: The authors and publisher of this book have used their     #
# best efforts in preparing the book. These efforts include the          #
# development, research, and testing of the theories and programs        #
# to determine their effectiveness. The authors and publisher make       #
# no warranty of any kind, expressed or implied, with regard to these    #
# programs or to the documentation contained in these books. The authors #
# and publisher shall not be liable in any event for incidental or       #
# consequential damages in connection with, or arising out of, the       #
# furnishing, performance, or use of these programs.                     #
##########################################################################